version: "3"

services:
  workspace:
    container_name: bio2kg-workspace
    # image: ghcr.io/maastrichtu-ids/jupyterlab:latest
    build: .
    # restart: unless-stopped
    volumes:
      - .:/home/jovyan/work
    user: "root"
    command: "--NotebookApp.token=''"
    environment:
      - DBA_PASSWORD=${VIRTUOSO_PASSWORD:-dba}
    #   - JUPYTER_TOKEN=password
    ports:
      - 8888:8888
