name: Process DrugBank
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'datasets/DrugBank/*'
    - '.github/workflows/process-drugbank.yml'
  # schedule:
  #   - cron:  '00 01 * * *'
  # Everyday at 01:00am GMT+1

jobs:

  process:
    runs-on: ["self-hosted", "dsri", "bio2kg" ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        conda install -y --file requirements.txt

    - name: Run ETL script
      env:
        DRUGBANK_USERNAME: ${{ secrets.DRUGBANK_USERNAME }}
        DRUGBANK_PASSWORD: ${{ secrets.DRUGBANK_PASSWORD }}
      run: |
        python datasets/DrugBank/load_drugbank.py

    - name: Upload CSV output
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: datasets/DrugBank/data/drugbank_processed.csv

    # Now with the RML mappings
    - name: Run RML mapper ETL
      env:
        DBA_PASSWORD: ${{ secrets.VIRTUOSO_PASSWORD }}
        DRUGBANK_USERNAME: ${{ secrets.DRUGBANK_USERNAME }}
        DRUGBANK_PASSWORD: ${{ secrets.DRUGBANK_PASSWORD }}
        DRUGBANK_VERSION: 5-1-8
      run: |
        cd datasets/DrugBank
        ./run.sh "-Xms32g -Xmx32g" || exit 1
        # curl -u dav:$DBA_PASSWORD --data-binary @data/bio2kg-drugbank.ttl -H "Accept: text/turtle" -H "Content-type: text/turtle" -H "Slug: drugbank" https://triplestore-bio2kg.apps.dsri2.unimaas.nl/DAV/ldp

    - name: Upload RDF output
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: datasets/DrugBank/data/bio2kg-drugbank.ttl