name: STITCH
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'datasets/STITCH/*'
    - '.github/workflows/process-stitch.yml'
  # schedule:
  #   - cron:  '00 01 * * *'
  # Everyday at 01:00am GMT+1

jobs:

  process:
    runs-on: ["self-hosted", "dsri", "bio2kg" ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run RML mapper ETL
      env:
        DBA_PASSWORD: ${{ secrets.VIRTUOSO_PASSWORD }}
      run: |
        pip install git+https://github.com/MaastrichtU-IDS/d2s-cli.git@master
        cd datasets/STITCH
        d2s run --memory 64g

    - name: Upload RDF output
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: datasets/STITCH/output/*