name: Process DrugBank
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'datasets/drugbank'
    - '.github/workflows/process-drugbank.yml'
  # schedule:
  #   - cron:  '00 01 * * *'
    # Everyday at 01:00am GMT+1

jobs:

  process:
    runs-on: ["self-hosted", "dsri", "bio2kg" ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Check 
      run: |
        pwd
        id

    - name: Install dependencies
      run: |
        conda install -y --file requirements.txt

    - name: Run ETL script
      env:
        DRUGBANK_PASSWORD: ${{ secrets.DRUGBANK_PASSWORD }}
      run: |
        python datasets/drugbank/load_drugbank.py

    - name: Upload CSV input artifact
      uses: actions/upload-artifact@v1
      with:
        name: output
        path: datasets/drugbank/data/drugbank_processed.csv