name: InterPro
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'datasets/InterPro/*'
    - '.github/workflows/process-interpro.yml'
  # schedule:
  #   - cron:  '00 01 * * *'
  # Everyday at 01:00am GMT+1

jobs:

  process-interpro:
    runs-on: ["self-hosted", "dsri", "bio2kg" ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run RML mapper ETL
      env:
        DBA_PASSWORD: ${{ secrets.VIRTUOSO_PASSWORD }}
      run: |
        cd datasets/InterPro
        ./download.sh
        ./run.sh "-Xms60g -Xmx60g"
        curl -u dav:$DBA_PASSWORD --data-binary @data/bio2kg-interpro.ttl -H "Accept: text/turtle" -H "Content-type: text/turtle" -H "Slug: interpro" https://triplestore-bio2kg.apps.dsri2.unimaas.nl/DAV/ldp

    - name: Upload RDF output
      uses: actions/upload-artifact@v2
      with:
        name: rdf-output
        path: datasets/InterPro/data/bio2kg-*.n3