name: Process DrugBank
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'datasets/drugbank'
    - '.github/workflows/process-drugbank.yml'
  # schedule:
  #   - cron:  '00 01 * * *'
    # Everyday at 01:00am GMT+1

jobs:

  process:
    runs-on: ["self-hosted", "dsri", "bio2kg" ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Hello 
      run: |
        echo "Hello bio2kg"
        mkdir testfolder
        pwd
        id

    - name: Update 
      run: |
        conda install -y --file requirements.txt
        conda install -y php

    - name: Run ETL script
      run: |
        python datasets/check.py
      # python datasets/drugbank/load_drugbank.py

    # - name: Install dependencies
    #   run: |
    #     pip install -r requirements.txt