name: Process HGNC
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'datasets/hgnc/*'
    - '.github/workflows/process-hgnc.yml'
  # schedule:
  #   - cron:  '00 01 * * *'
  # Everyday at 01:00am GMT+1

jobs:

  process:
    runs-on: ["self-hosted", "dsri", "bio2kg" ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Run RML mapper ETL
      run: |
        cd datasets/hgnc
        ./run.sh

    - name: Upload RDF output
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: datasets/hgnc/data/bio2kg-hgnc.ttl