name: DrugBank
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'datasets/DrugBank/*'
    - '.github/workflows/process-drugbank.yml'
  # schedule:
  #   - cron:  '00 01 * * *'
  # Everyday at 01:00am GMT+1

jobs:

  process-drugbank:
    runs-on: ["self-hosted", "dsri", "bio2kg" ]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    # - name: Install dependencies
    #   run: |
    #     conda install -y --file requirements.txt

    # - name: Run python ETL script
    #   env:
    #     DRUGBANK_USERNAME: ${{ secrets.DRUGBANK_USERNAME }}
    #     DRUGBANK_PASSWORD: ${{ secrets.DRUGBANK_PASSWORD }}
    #   run: |
    #     python datasets/DrugBank/load_drugbank.py

    # - name: Upload CSV output
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: output
    #     path: datasets/DrugBank/data/drugbank_processed.csv

    # # Run with the RML mapper, seems to time out
    # - name: Run RML mapper ETL
    #   env:
    #     DBA_PASSWORD: ${{ secrets.VIRTUOSO_PASSWORD }}
    #     DRUGBANK_USERNAME: ${{ secrets.DRUGBANK_USERNAME }}
    #     DRUGBANK_PASSWORD: ${{ secrets.DRUGBANK_PASSWORD }}
    #     DRUGBANK_VERSION: 5-1-8
    #   run: |
    #     cd datasets/DrugBank
    #     ./run.sh "-Xms100g -Xmx100g"
    #     ./download.sh
    #     curl -u dav:$DBA_PASSWORD --data-binary @data/bio2kg-drugbank.ttl -H "Accept: text/turtle" -H "Content-type: text/turtle" -H "Slug: drugbank" https://triplestore-bio2kg.apps.dsri2.unimaas.nl/DAV/ldp

    - name: Run dataset processing
      env:
        DBA_PASSWORD: ${{ secrets.VIRTUOSO_PASSWORD }}
        DRUGBANK_USERNAME: ${{ secrets.DRUGBANK_USERNAME }}
        DRUGBANK_PASSWORD: ${{ secrets.DRUGBANK_PASSWORD }}
        DRUGBANK_VERSION: 5-1-8
      run: |
        pip install git+https://github.com/MaastrichtU-IDS/d2s-cli.git@master
        cd datasets/DrugBank
        d2s run --memory 32g

    # https://github.com/redhat-actions/oc-login#readme
    # - name: Log in to OpenShift
    #   uses: redhat-actions/oc-login@v1
    #   with:
    #     openshift_server_url: https://api.dsri2.unimaas.nl:6443
    #     openshift_username: ${{ secrets.OPENSHIFT_USERNAME }}
    #     openshift_password: ${{ secrets.OPENSHIFT_PASSWORD }}
    #     insecure_skip_tls_verify: true
    #     namespace: bio2kg

    # - name: Run RML Streamer ETL
    #   env:
    #     DBA_PASSWORD: ${{ secrets.VIRTUOSO_PASSWORD }}
    #     DRUGBANK_USERNAME: ${{ secrets.DRUGBANK_USERNAME }}
    #     DRUGBANK_PASSWORD: ${{ secrets.DRUGBANK_PASSWORD }}
    #     DRUGBANK_VERSION: 5-1-8
    #   run: |
    #     cd datasets/DrugBank
    #     # oc login --username=${{ secrets.OPENSHIFT_USERNAME }} --password=${{ secrets.OPENSHIFT_PASSWORD }} --server=https://api.dsri2.unimaas.nl:6443
    #     ./run_rmlstreamer.sh
    #     head -n 100 data/bio2kg-drugbank.ttl
    #     # curl -u dav:$DBA_PASSWORD --data-binary @data/bio2kg-drugbank.ttl -H "Accept: text/turtle" -H "Content-type: text/turtle" -H "Slug: drugbank" https://triplestore-bio2kg.apps.dsri2.unimaas.nl/DAV/ldp
        
    
    # - name: Run RocketRML mapper ETL
    #   env:
    #     DBA_PASSWORD: ${{ secrets.VIRTUOSO_PASSWORD }}
    #     DRUGBANK_USERNAME: ${{ secrets.DRUGBANK_USERNAME }}
    #     DRUGBANK_PASSWORD: ${{ secrets.DRUGBANK_PASSWORD }}
    #     DRUGBANK_VERSION: 5-1-8
    #   run: |
    #     conda install -y pugixml
    #     conda install -y -c anaconda make gcc
    #     yarn
    #     cd datasets/DrugBank
    #     ./download.sh $DRUGBANK_USERNAME $DRUGBANK_PASSWORD
    #     ./run.sh
    #     # curl -u dav:$DBA_PASSWORD --data-binary @data/bio2kg-drugbank.ttl -H "Accept: text/turtle" -H "Content-type: text/turtle" -H "Slug: drugbank" https://triplestore-bio2kg.apps.dsri2.unimaas.nl/DAV/ldp
        

    - name: Upload RDF output
      uses: actions/upload-artifact@v2
      with:
        name: rdf-output
        path: datasets/DrugBank/data/bio2kg-*.n3